# Configuración adicional
configuracion:
  tipo_diagnostico: "D"
  archivo_entrada: "files/input.xlsx"
  archivo_salida: "files/final_{timestamp}.csv"  # Nombre único con timestamp
  generar_nombre_unico: true  # Generar nombre único para cada ejecución
  
# Columnas a mantener en el dataset final
columnas:
  - Numero_Documento_Paciente
  - Genero
  - Edad_Reg
  - Codigo_Item
  - Tipo_Diagnostico
  - Valor_Lab
  - Id_Correlativo
  - Perimetro_Abdominal
  - Fecha_Atencion
  - Nombre_Establecimiento

# Reglas de validación
validaciones:
  edad_minima: 0
  edad_maxima: 120
  generos_validos: ["M", "F"]

# # Sobre peso
# # Códigos de item médicos a filtrar
# codigos_item:
#   obligatorios:  # Códigos que DEBEN estar presentes
#     - "Z019"
#     - "E6690"
# # Modo de filtrado para códigos de item
# filtrado_codigos:
#   modo: "todos"

# # Sobre obesidad
# # Códigos de item médicos a filtrar
# codigos_item:
#   obligatorios:  # Códigos que DEBEN estar presentes
#     - "Z019"
#     - "E669"
# # Modo de filtrado para códigos de item
# filtrado_codigos:
#   modo: "todos"

# # Sobre obesidad tipo 1
# # Códigos de item médicos a filtrar
# codigos_item:
#   obligatorios:  # Códigos que DEBEN estar presentes
#     - "Z019"
#     - "E6691"
# # Modo de filtrado para códigos de item
# filtrado_codigos:
#   modo: "todos"

# # Sobre obesidad tipo 2
# # Códigos de item médicos a filtrar
# codigos_item:
#   obligatorios:  # Códigos que DEBEN estar presentes
#     - "Z019"
#     - "E6692"
# # Modo de filtrado para códigos de item
# filtrado_codigos:
#   modo: "todos"

# # Sobre obesidad tipo 3
# # Códigos de item médicos a filtrar
# codigos_item:
#   obligatorios:  # Códigos que DEBEN estar presentes
#     - "Z019"
#     - "E6693"
# # Modo de filtrado para códigos de item
# filtrado_codigos:
#   modo: "todos"

# # Dislipidemia
# # Códigos de item médicos a filtrar
# codigos_item:
#   obligatorios:  # Códigos que DEBEN estar presentes
#     - "Z019"
#   opcionales:
#     - "E780"
#     - "E781"
#     - "E782"
#     - "E785"
# # Modo de filtrado para códigos de item
# filtrado_codigos:
#   modo: "todos"

# # Presión arterial Enero Junio 2025
# filtro_especifico:
#   activo: true  # true = aplicar filtro específico, false = no aplicar
#   tipo_diagnostico: ["D", "R"]  # Puede ser D o R
#   codigo_item_especifico: "99199.22"  # Código específico a filtrar
#   valor_lab_especifico: ["N", "A"]  # Valores específicos de laboratorio (N o A)
#   fecha_atencion_rango: ["2025-01-01", "2025-06-30"]  # Rango de fechas de atención
# filtrado_codigos:
#   modo: "todos"

# # Presión arterial Julio Septiembre 2025
# filtro_especifico:
#   activo: true  # true = aplicar filtro específico, false = no aplicar
#   tipo_diagnostico: ["D", "R"]  # Puede ser D o R
#   codigo_item_especifico: "99199.22"  # Código específico a filtrar
#   tipo_presion_arterial_activo: true  # true = aplicar filtro específico, false = no aplicar
#   tipo_presion_arterial: ["S", "D"]  # Puede ser S (Sistólica) o D (Diastólica)
#   fecha_atencion_rango: ["2025-07-01", "2025-09-30"]  # Rango de fechas de atención
# filtrado_codigos:
#   modo: "todos"

# # Presión arterial Julio Diciembre 2025
# filtro_especifico:
#   activo: true  # true = aplicar filtro específico, false = no aplicar
#   tipo_diagnostico: ["D", "R"]  # Puede ser D o R
#   codigo_item_especifico: "99199.22"  # Código específico a filtrar
#   tipo_presion_arterial_activo: true  # true = aplicar filtro específico, false = no aplicar
#   tipo_presion_arterial: ["S", "D"]  # Puede ser S (Sistólica) o D (Diastólica)
#   fecha_atencion_rango: ["2025-07-01", "2025-12-31"]  # Rango de fechas de atención
# filtrado_codigos:
#   modo: "todos"

# # Filtro de códigos con clasificación de perímetro abdominal
# filtro_perimetro:
#   activo: true  # true = aplicar filtro de perímetro, false = no aplicar
#   codigos_requeridos:  # Códigos que DEBEN estar presentes para este filtro
#     - "Z019"
#     - "99209.04"
#   clasificacion_perimetro:
#     genero_femenino:
#       normal: 88  # <= 88 es normal
#       anormal: 88  # > 88 es anormal
#     genero_masculino:
#       normal: 102  # <= 102 es normal
#       anormal: 102  # > 102 es anormal
#   fecha_atencion_activo: true  # true = aplicar filtro de fecha de atención, false = no aplicar
#   modo_filtrado: "todos"  # "todos" = pacientes con TODOS los códigos requeridos

# # Filtro de valoración clínica sin factores de riesgo
# filtro_valoracion_clinica:
#   activo: true  # true = aplicar filtro de valoración clínica, false = no aplicar
#   codigos_requeridos:  # Códigos que DEBEN estar presentes para este filtro
#     - "Z019"
#     - "Z006"
#   valor_lab_especifico: ["IMC"]  # Valores específicos de laboratorio 
#   fecha_atencion_activo: true  # true = aplicar filtro de fecha de atención, false = no aplicar
#   modo_filtrado: "todos"  # "todos" = pacientes con TODOS los códigos requeridos


# # Filtro de valoración clínica con factores de riesgo
# filtro_valoracion_clinica_con_riesgo:
#   activo: true  # true = aplicar filtro de valoración clínica con riesgo, false = no aplicar
#   codigos_requeridos:  # Códigos que DEBEN estar presentes para este filtro
#     - "Z019"
#   codigos_factores_riesgo:  # Códigos de factores de riesgo (al menos uno debe estar presente)
#     - "E65X"
#     - "E669"
#     - "E6691"
#     - "E6692"
#     - "E6693"
#     - "E6690"
#   valor_lab_especifico: ["IMC"]  # Valores específicos de laboratorio
#   fecha_atencion_activo: true  # true = aplicar filtro de fecha de atención, false = no aplicar
#   modo_filtrado: "todos"  # "todos" = pacientes con TODOS los códigos requeridos

# # Filtro de valoración clínica con factores de riesgo y laboratorio
# filtro_valoracion_clinica_con_riesgo:
#   activo: true  # true = aplicar filtro de valoración clínica con riesgo, false = no aplicar
#   codigos_requeridos:  # Códigos que DEBEN estar presentes para este filtro
#     - "Z019"
#     - "Z017"
#   codigos_factores_riesgo:  # Códigos de factores de riesgo (al menos uno debe estar presente)
#     - "E65X"
#     - "E669"
#     - "E6691"
#     - "E6692"
#     - "E6693"
#     - "E6690"
#   valor_lab_especifico: ["IMC"]  # Valores específicos de laboratorio
#   fecha_atencion_activo: true  # true = aplicar filtro de fecha de atención, false = no aplicar
#   modo_filtrado: "todos"  # "todos" = pacientes con TODOS los códigos requeridos


# # Filtro de valoración clínica y laboratorio
# filtro_valoracion_clinica_con_riesgo:
#   activo: true  # true = aplicar filtro de valoración clínica con riesgo, false = no aplicar
#   codigos_requeridos:  # Códigos que DEBEN estar presentes para este filtro
#     - "Z019"
#     - "Z017"
#   codigos_factores_riesgo: [] # Códigos de factores de riesgo (al menos uno debe estar presente)
#   # valor_lab_especifico: ["IMC"]  # Valores específicos de laboratorio
#   fecha_atencion_activo: true  # true = aplicar filtro de fecha de atención, false = no aplicar
#   modo_filtrado: "todos"  # "todos" = pacientes con TODOS los códigos requeridos  

# # Filtro de Consejeria estilo de vida
# filtro_valoracion_clinica_con_riesgo:
#   activo: true  # true = aplicar filtro de valoración clínica con riesgo, false = no aplicar
#   codigos_requeridos:  # Códigos que DEBEN estar presentes para este filtro
#     - "99401.13"
#     - "Z019"
#   codigos_factores_riesgo:  # Códigos de factores de riesgo (al menos uno debe estar presente)
#     - "E669"
#     - "E6691"
#     - "E6692"
#     - "E6693"
#     - "E6690"
#     - "E785"
#     - "Z006"
#   valor_lab_especifico: ["IMC"]  # Valores específicos de laboratorio
#   fecha_atencion_activo: true  # true = aplicar filtro de fecha de atención, false = no aplicar
#   modo_filtrado: "todos"  # "todos" = pacientes con TODOS los códigos requeridos

# #Filtro de riesgo cardiovascular
# filtro_especifico:
#   activo: true  # true = aplicar filtro específico, false = no aplicar
#   tipo_diagnostico: ["D"]  # Puede ser D
#   codigo_item_especifico: "99199.23"  # Código específico a filtrar
# filtrado_codigos:
#   modo: "todos"